#:schema node_modules/wrangler/config-schema.json
name = "demo-elite-xv-rosa"
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]

# Corregido: Ahora es un string simple como pide el error
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyDz23jhxeFZ4rkj4aGF1-kZUtZwy_2f7g0"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "invitaciones-max-pro.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "invitaciones-max-pro"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "invitaciones-max-pro.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "1098024307251"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:1098024307251:web:60b7acb9fbde1194c97146"